#!/bin/sh

echo "Installing web.py"
tar xzvf /tmp/web.py-0.34.tar.gz
cd web.py-0.34
python setup.py install

echo "Making backup staging directory accessible to Apache"
chown -R www-data /innobackup/mediawiki
chown -R www-data /var/www/innobox-backup/banners

echo "Enabling mod_include"
ln -s /etc/apache2/mods-available/include.load /etc/apache2/mods-enabled/
