#!/bin/sh

######### 
#Variables
#########

backupdirname="InnoboxMediaWikiBackupv1"
mountpt="/mnt/backup"

backupPath=$mountpt/$backupdirname/

LocalSettings="/etc/mediawiki/LocalSettings.php"
dumpBackup="/usr/share/mediawiki/maintenance/dumpBackup.php"
Images="/var/lib/mediawiki/images/"
wikiPass=`cat/etc/mediawiki/wiki_password.txt`


##########

#########




echo "Dumping the MySQL Database"

#Dump the MySQL database
/usr/bin/nice -n 19 mysqldump -uwiki_user -p$wikiPass --add-drop-table wiki_db -c 

echo "Taring the image files and LocalSettings"

#Create a tar of all of the associate files:
/usr/bin/nice -n 19 tar -czvf $backupdir/wiki-supportfiles-$timestamp.tgz $LocalSettings $Images


sleep 1
echo "Starting the XML Dump"

/usr/bin/nice -n 19 php  $dumpBackup --full | gzip > $backupdir/wiki-XML-$timestamp.xml.gz


echo "Finished"   
exit 0




